name: Simple_Draw_Paint
description: This is Simple Draw Paint App .

publish_to: "none"

version: 1.0.1+7

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Multi language
  flutter_localizations:
    sdk: flutter
  image_painter:
    path: packages/mage_painter/
  intl:
  # open_file: ^3.2.1
  path_provider: ^2.0.9
  cupertino_icons: ^1.0.5
  google_mobile_ads: ^5.1.0
  gma_mediation_pangle: ^1.1.0

  image_gallery_saver:
    git:
      url: https://github.com/knottx/image_gallery_saver.git
      ref: knottx-latest
  flutter_launcher_icons: ^0.13.1
  open_file: ^3.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true #追加

  assets:
    - assets/images/
    - assets/sample.png
    - assets/sample.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
